### ISSUE TITLE
Linux support?

### ISSUE THREAD

**Issue by advaithm** [lionloya/NightPDF#1]
i would love to use NightPDF but it doesn't support linux so i can not. please support linux. if don't want to make binary at-least make a flatpak version

**Comment by drapado** [comment]
I completely agree! Linux support would be great! (awesome work btw!)

**Comment by advaithm** [comment]
based on some testing it does work out of the box. I don't see why it can't be packaged for Linux distributions with some minor ui tweaks

**Comment by joeloya** [comment]
Happy to do it this weekend.

**Comment by advaithm** [comment]
Nice

**Comment by advaithm** [comment]
any updates on this @joeloya

**Comment by RashiqAzhan** [comment]
Came here to second the Linux support. Would really appreciate it.

**Comment by advaithm** [comment]
@lionloya please update us on the status of this.

**Comment by advaithm** [comment]
I have started on a linux port however i am not very experienced in js. I believe the next order after porting it should be updating the electron version

**Comment by advaithm** [comment]
can someone help me resize the ico file?

**Comment by advaithm** [comment]
nvm i got it

**Comment by advaithm** [comment]
I have a working linux port I will be making releases on my fork until this is merged into the main fork.

**Comment by advaithm** [comment]
I will also fix issues found in the main project until this is merged into the main fork I plan to start with #4

**Comment by advaithm** [comment]
Since my fork has been merged I am closing this issue
